language: node_js
node_js: node

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: "test"
      script: npm test
    - stage: deploy
      name: "npm & GitHub"
      script: skip
      deploy:
        provider: script
        script: npx semantic-release --dry
        skip_cleanup: true
        on:
          all_branches: true # semantic-release has a regex that allows us to publish maintenance releases
